### PR TITLE
start port to python 3 (tests mostly pass)

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by glyph** [comment]
These build errors seem to be fairly silly CI-configuration issues, so I can't see if there's anything interesting going on with the failures on py3.

**Comment by graingert** [comment]
@glyph I don't even remember making this PR, thanks for taking it over

**Comment by glyph** [comment]
@graingert thanks for getting it started!

**Comment by palfrey** [comment]
Any chance of a new release out with these fixes? I'm trying to [upgrade Axiom to Python 3](https://github.com/twisted/axiom/pull/119) and running into build issues because it's still using the last released Epsilon

**Comment by mithrandi** [comment]
> Any chance of a new release out with these fixes? I'm trying to [upgrade Axiom to Python 3](https://github.com/twisted/axiom/pull/119) and running into build issues because it's still using the last released Epsilon

Done! https://pypi.org/project/epsilon/0.8.0/

**Pull request merged**
